# Generated by Django 5.1.1 on 2024-10-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='url',
            field=models.URLField(auto_created=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='views_limit',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
