# Generated by Django 5.1.1 on 2024-10-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_note_url_alter_note_views_limit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
