# Generated by Django 5.1.1 on 2024-10-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
