# Generated by Django 5.1.1 on 2024-10-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='url',
            field=models.UUIDField(auto_created=True, editable=False, unique=True),
        ),
    ]
