# Generated by Django 5.1.1 on 2024-10-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_note_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
